exclude: (.*/bin/.*|.*/obj/.*)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
        args:
          - "-r ~MD013"
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.2
    hooks:
      - id: actionlint
  - repo: https://github.com/crate-ci/typos
    rev: v1.24.6
    hooks:
      - id: typos
  # C# settings
  - repo: local
    hooks:
      # - id: dotnet-tool-restore
      #   name: Install .NET tools
      #   entry: dotnet tool restore
      #   # for pre-commit < 4.4.0 use language: system
      #   language: unsupported
      #   always_run: true
      #   pass_filenames: false
      #   stages:
      #     - pre-commit
      #     - pre-push
      #     - post-checkout
      #     - post-rewrite
      #   description: Install the .NET tools listed at .config/dotnet-tools.json.
      - id: csharpier
        name: Run CSharpier on C# files
        entry: csharpier format
        language: system
        types:
          - c#
        description: CSharpier is an opinionated C# formatter inspired by Prettier.
